# 1.4 판다스, 데이터 핸들링

In [46]:
import pandas as pd
import numpy as np

#### 1. 데이터 살펴보기

In [47]:
titanic_df = pd.read_csv(r"C:\Users\willi\바탕 화면\중앙대학교\CUAI\머신러닝 스터디\titanic\train.csv")
titanic_df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic_df.shape
#(891, 12) --> 891개 데이터, 12개 feature

(891, 12)

In [7]:
titanic_df.info()
# row: 891개, column: 12개
# Age에 대해 714개의 값만 존재 --> 나머지는 NULL값으로 처리되어 있음
# ㄴ-> Cabin, Embarked도 마찬가지 NULL값 존재

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
titanic_df.describe()
# 데이터의 feature별 특징을 알 수 있음(!단, 숫자 자료형에 대해서만 출력!)
# 1. PassengerId: 1~891까지 각 데이터에 부여된 수 --> 큰 의미 없음
# 2. Survived: 0, 1로 이루어진 categorical한 피쳐임을 알 수 있음 
# 3. Pclass: 1, 2, 3값만 있는 카테고리컬한 피쳐
# 4. Age: 나이임, 0.42살은 뭐냐
# 5. SibSp: 형제자매, 배우자 동승 수 0~8
# 6. Parch: 부모님, 자녀 동승 수 0~6
# 7. Fare: 선착장 번호

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
# 데이터에 대해 좀 더 알아봅시다

# df_name.value_counts(dropna = True) --> value 별 데이터의 개수 리턴,  NULL값 고려? T/F
value_counts_Pclass = titanic_df['Pclass'].value_counts()
print(value_counts_Pclass)

value_counts_Embarked = titanic_df['Embarked'].value_counts(dropna = False)
print(value_counts_Embarked, '\n')
# NULL값 두 개 

# titanic_df[Pclass]--> series 형태로 출력
# ㄴ-> series == index + value (series가 합쳐져 df를 이룸)
Pclass = titanic_df['Pclass']
print(type(Pclass))
Pclass.head()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

<class 'pandas.core.series.Series'>

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

#### 2. DF에서의 리스트, 딕셔너리, ndarray

In [2]:
import numpy as np
lst = [1, 2, 3]
ndarr = np.array(lst)

# 1. list --> df
df_lst = pd.DataFrame(lst, columns = ['column1'])
print(df_lst, '\n')

# 2. ndarray --> df
df_ndarr = pd.DataFrame(ndarr, columns = ['columns2'])
print(df_ndarr)

# +)column 여러개
col_name = ['col1', 'col2', 'col3']
lst2 = [[1, 2, 3], [4, 5, 6]]
df_lst2 = pd.DataFrame(lst2, columns = col_name)
print(df_lst2, '\n')

# 3. dict --> df
# key --> 칼럼명, value = 해당 칼럼의 데이터
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

#---------------------------------------------------------

# 4. df --> ndarray
arr = df_dict.values
print(arr, '\n')

# 5. df --> list
# 정확히 하면 df --> ndarray --> list
# np.tolist()
lst = df_dict.values.tolist()
print(lst)

# 6. df --> dict
dict = df_dict.to_dict('list') # column --> key, column의 value(리스트 형태) --> value
print(dict)

   column1
0        1
1        2
2        3

   columns2
0         1
1         2
2         3
   col1  col2  col3
0     1     2     3
1     4     5     6

   col1  col2  col3
0     1     2     3
1    11    22    33
[[ 1  2  3]
 [11 22 33]]

[[1, 2, 3], [11, 22, 33]]
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

#### 3. df 칼럼 데이터 세트 수정

In [8]:
# df 칼럼 데이터 생성, 수정은 그냥 하면 됨;;
titanic_df['Age_0'] = 0
titanic_df.head(3)

# df 줄 삭제 
# df_name.drop('name', index = 1, inplace = False) --> 칼럼 삭제
titanic_df_drop = titanic_df.drop('Age_0', axis = 1, inplace = False)
titanic_df_drop.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [9]:
# Age_0 칼럼이 삭제됨을 알 수 있음
# inplace = True --> 반환값 None, 해당 df 변환
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [10]:
# 암기할꺼...
# 2차원 ndarray에서 
# axis = 0 --> row / axis = 1 --> column
# axis가 클 수록 깊은거 지정

In [11]:
# 0, 1, 2 row 삭제
titanic_df.drop([0, 1, 2], axis = 0, inplace = True)
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,0

### 4. Index 객체

In [4]:
# 원본 파일 다시 불러오기 
titanic_df = pd.read_csv(r"C:\Users\willi\바탕 화면\중앙대학교\CUAI\머신러닝 스터디\titanic\train.csv")
# index객체 추출(index == row)
indexes = titanic_df.index
print(indexes)
print(indexes.values) # 0~890

RangeIndex(start=0, stop=891, step=1)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [5]:
# pd.index 주의사항!
# 만들어지 index 객체의 값을 수정할 수 없음!
try:
    indexes[5] = 0
except TypeError:
    print('Can\'t do that')

# df_name.reset_index(inplace = False)
titanic_df = titanic_df.reset_index()
titanic_df.head(3)
# 기존 index는 index칼럼 생성 --> 이 안으로 들어감

Can't do that

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

여러가지 df 기능들

In [8]:
# df.value_counts(inplace = False)
Pclass_values = titanic_df['Pclass'].value_counts()
print(Pclass_values, '\n')

# df에서의 []연산자
# 슬라이싱
print(titanic_df['Pclass'][:2], '\n') # 이 방식보단 df.iloc 방식을 지향하라고 함

# 조건 부여
print(titanic_df[titanic_df['Pclass'] == 3].head(3)) # bolean 인덱싱 쪼아요ㅗ

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

0    3
1    1
Name: Pclass, dtype: int64

   PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0
2            3         1       3    Heikkinen, Miss. Laina  female  26.0
4            5         0       3  Allen, Mr. William Henry    male  35.0

   SibSp  Parch            Ticket   Fare Cabin Embarked
0      1      0         A/5 21171  7.250   NaN        S
2      0      0  STON/O2. 3101282  7.925   NaN        S
4      0      0            373450  8.050   NaN        S

#### 좀 더 정석적인 df 인덱싱 방법  
df_name.iloc()  
df_name.loc()

In [9]:
# df_name.iloc[](중요!)
# location(위치)기반 인덱싱 방식,  element로 행/열 순서로 입력 
# 1. df_name.iloc[1, 2] --> 2행 3열 값 반환
# 2. dF_name.iloc[[0, 2], :3] --> 1,3행, 1~3행 반환
# $$ 유의!! .iloc은 boolean 인덱싱 불가! $$

# df_name.loc[](중요!)
# 행렬 Label(명칭)기반 인덱싱 방식, "
# 1. df_name.loc[0, 'Pclass'] 1행, 'Pclass'열 값 반환
# 2. df_name.loc[0:2, ['Pclass', 'Embark']] 1~3행, 'Pclass', 'Embarked'열 반환 
# $$ df 정의할 때 index 이름을 지정한 경우, 해당 열의 index로 불러와야 함! $$

# 공통 유의사항: inplace 인자가 딱히 없어서 수정 그냥 하면 됨

#### 또 왔습니다 대충 여러가지 df 기능들

In [17]:
# df_name.sort_values(by = '?', inplace = 'False', ascending = 'True')
# by: 정렬 기준 / inplace: df_name 갱신 / ascending: 오름차순
titanic_sorted = titanic_df.sort_values(by = ['Name'], inplace = False, ascending = True)
print(titanic_sorted.head(3), '\n')

#  기준이 두 개 이상일 때, 내림차순 
titanic_sorted.sort_values(by = ['Name', 'Sex'], inplace = True, ascending  = False)
print(titanic_sorted.head(10)) # 앞에 기준 먼저 --> 겹치면 뒤에 기준

     PassengerId  Survived  Pclass                              Name     Sex  \
845          846         0       3               Abbing, Mr. Anthony    male
746          747         0       3       Abbott, Mr. Rossmore Edward    male
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845  42.0      0      0  C.A. 5547   7.55   NaN        S
746  16.0      1      1  C.A. 2673  20.25   NaN        S
279  35.0      1      1  C.A. 2673  20.25   NaN        S

     PassengerId  Survived  Pclass  \
868          869         0       3
153          154         0       3
361          362         0       2
282          283         0       3
286          287         1       3
559          560         1       3
422          423         0       3
240          241         0       3
111          112         0       3
199          200         0       2

                                             Name     Sex   Age  SibSp  Parch  \
868                   van Melkebeke, Mr. Philemon    male   NaN      0      0
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2
361                     del Carlo, Mr. Sebastiano    male  29.0      1      0
282                     de Pelsmaeker, Mr. Alfons    male  16.0      0      0
286                       de Mulder, Mr. Theodore    male  30.0      0      0
559  de Messemaeker, Mrs. Guillaume Joseph (Emma)  female  36.0      1      0
422                            Zimmerman, Mr. Leo    male  29.0      0      0
240                         Zabour, Miss. Thamine  female   NaN      1      0
111                          Zabour, Miss. Hileni  female  14.5      1      0
199        Yrois, Miss. Henriette ("Mrs Harbeck")  female  24.0      0      0

            Ticket     Fare Cabin Embarked
868         345777   9.5000   NaN        S
153       A/5. 851  14.5000   NaN        S
361  SC/PARIS 2167  27.7208   NaN        C
282         345778   9.5000   NaN        S
286         345774   9.5000   NaN        S
559         345572  17.4000   NaN        S
422         315082   7.8750   NaN        S
240           2665  14.4542   NaN        C
111           2665  14.4542   NaN        C
199         248747  13.0000   NaN        S

In [30]:
# 1. 각종 연산 기능들
# .sum(), .mean(), .count(), .min(), .max()

# 2. df_name.groupby() 같은거끼리 묶어서 재정렬
titanic_df_groupby = titanic_df.groupby(by = ['Pclass'])
print(titanic_df_groupby.count())

# 3. df_name.agg([함수])
# 이제 힘들어서 그냥 넘어가겠음

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass
1               216       216   216  216  186    216    216     216   216
2               184       184   184  184  173    184    184     184   184
3               491       491   491  491  355    491    491     491   491

        Cabin  Embarked
Pclass
1         216       214
2         184       184
3         491       491

#### 결손 데이터 처리

In [55]:
# 1. 결손 데이터 확인
# df_name.isna()
print(titanic_df.isna().sum(), '\n') # 여기에 sum하는데 왜 이렇게 되냐 신기하노

# 2. 결손 데이터 채우기 
# df_name.fillna()
# 'Cabin' 열
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df[titanic_df['Cabin'] == 'C000'].head(5)

# 'Age' 열
# 남자na --> 남자 중간값 / 여자na --> 여자 중간값
# 내가 따로 한거 ★
male_age_mid = titanic_df.loc[titanic_df['Sex'] == 'male', ['Age']].median()
female_age_mid = titanic_df.loc[titanic_df['Sex'] == 'female', ['Age']].median()
titanic_df.loc[titanic_df['Sex'] == 'male', ['Age']] = titanic_df.loc[titanic_df['Sex'] == 'male', ['Age']].fillna(male_age_mid)
titanic_df.loc[titanic_df['Sex'] == 'female', ['Age']] = titanic_df.loc[titanic_df['Sex'] == 'female', ['Age']].fillna(female_age_mid)
print(titanic_df.loc[:, ['Age', 'Sex']].head(15))

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

     Age     Sex
0   22.0    male
1   38.0  female
2   26.0  female
3   35.0  female
4   35.0    male
5   29.0    male
6   54.0    male
7    2.0    male
8   27.0  female
9   14.0  female
10   4.0  female
11  58.0  female
12  20.0    male
13  39.0    male
14  14.0  female

#### lambda를 이용한 데이터 가공

In [56]:
# lamda 사용 예시
lambda_square = lambda x: x**2 # x 입력 인자, x**2 리턴할 값

# df_name.apply(?) --> df_name에 ? 함수 적용