# 1.4 판다스, 데이터 핸들링

In [3]:
import pandas as pd

#### 1. 데이터 살펴보기

In [4]:
titanic_df = pd.read_csv(r"C:\Users\willi\바탕 화면\중앙대학교\CUAI\머신러닝 스터디\titanic\train.csv")
titanic_df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic_df.shape
#(891, 12) --> 891개 데이터, 12개 feature

(891, 12)

In [7]:
titanic_df.info()
# row: 891개, column: 12개
# Age에 대해 714개의 값만 존재 --> 나머지는 NULL값으로 처리되어 있음
# ㄴ-> Cabin, Embarked도 마찬가지 NULL값 존재

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
titanic_df.describe()
# 데이터의 feature별 특징을 알 수 있음(!단, 숫자 자료형에 대해서만 출력!)
# 1. PassengerId: 1~891까지 각 데이터에 부여된 수 --> 큰 의미 없음
# 2. Survived: 0, 1로 이루어진 categorical한 피쳐임을 알 수 있음 
# 3. Pclass: 1, 2, 3값만 있는 카테고리컬한 피쳐
# 4. Age: 나이임, 0.42살은 뭐냐
# 5. SibSp: 형제자매, 배우자 동승 수 0~8
# 6. Parch: 부모님, 자녀 동승 수 0~6
# 7. Fare: 선착장 번호

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [17]:
# 데이터에 대해 좀 더 알아봅시다

# df_name.value_counts(dropna = True) --> value 별 데이터의 개수 리턴,  NULL값 고려? T/F
value_counts_Pclass = titanic_df['Pclass'].value_counts()
print(value_counts_Pclass)

value_counts_Embarked = titanic_df['Embarked'].value_counts(dropna = False)
print(value_counts_Embarked, '\n')
# NULL값 두 개 

# titanic_df[Pclass]--> series 형태로 출력
# ㄴ-> series == index + value (series가 합쳐져 df를 이룸)
Pclass = titanic_df['Pclass']
print(type(Pclass))
Pclass.head()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

<class 'pandas.core.series.Series'>

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

#### 2. DF에서의 리스트, 딕셔너리, ndarray

In [9]:
import numpy as np
lst = [1, 2, 3]
ndarr = np.array(lst)

# 1. list --> df
df_lst = pd.DataFrame(lst, columns = ['column1'])
print(df_lst, '\n')

# 2. ndarray --> df
df_ndarr = pd.DataFrame(ndarr, columns = ['columns2'])
print(df_ndarr)

# +)column 여러개
col_name = ['col1', 'col2', 'col3']
lst2 = [[1, 2, 3], [4, 5, 6]]
df_lst2 = pd.DataFrame(lst2, columns = col_name)
print(df_lst2, '\n')

# 3. dict --> df
# key --> 칼럼명, value = 해당 칼럼의 데이터
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

#---------------------------------------------------------

# 4. df --> ndarray
arr = df_dict.values
print(arr, '\n')

# 5. df --> list
# 정확히 하면 df --> ndarray --> list
# np.tolist()
lst = df_dict.values.tolist()
print(lst)

# 6. df --> dict
dict = df_dict.to_dict('list') # dict 내부 value값을 list로 리턴
print(dict)

   column1
0        1
1        2
2        3

   columns2
0         1
1         2
2         3
   col1  col2  col3
0     1     2     3
1     4     5     6

   col1  col2  col3
0     1     2     3
1    11    22    33

#### 3. df 칼럼 데이터 세트 생성과 수정